#!/usr/bin/env python3
"""Build GPTs Knowledge bundle files from the generated llm-reference corpus."""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parents[2]
UPLOAD_DIR = SCRIPT_PATH.parent
ENCYCLOPEDIA = UPLOAD_DIR / "Altibase_GPT_Knowledge_Encyclopedia.md"
SCRIPT_REL_PATH = "llm-reference/gpts-upload/build-gpts-knowledge-bundles.py"

FULL_INCLUDE_SOURCE_PATHS = [
    "llm-reference/README.md",
    "llm-reference/source-index.md",
    "llm-reference/00-source-classification.md",
    "llm-reference/01-installation-upgrade-platform.md",
    "llm-reference/02-architecture-storage-concepts.md",
    "llm-reference/03-operation-administration-security.md",
    "llm-reference/04-backup-recovery.md",
    "llm-reference/05-replication-ha.md",
    "llm-reference/06-monitoring-diagnostics.md",
    "llm-reference/07-troubleshooting-error-messages.md",
    "llm-reference/08-sql-performance-tuning.md",
    "llm-reference/09-development-client-api.md",
    "llm-reference/10-application-framework-integration.md",
    "llm-reference/11-migration-conversion-tools.md",
    "llm-reference/12-terminology-multilingual-preservation.md",
]

SUPPORTING_SOURCE_PATHS = [
    "llm-reference/HANDOFF.md",
    "llm-reference/LLM_REFERENCE_BUILD_REPORT.md",
    "llm-reference/coverage/README.md",
]

REQUIRED_SOURCE_PATHS = FULL_INCLUDE_SOURCE_PATHS + SUPPORTING_SOURCE_PATHS

ANSWERING_RULES = """Use Altibase_GPT_Knowledge_Encyclopedia.md as the primary source for Altibase answers.
Answer from the uploaded knowledge file before relying on general knowledge.
Do not require access to original arch, FAQE, DOCK, or faq source files.
Prefer exact commands, SQL, file paths, configuration properties, system views, error codes, class names, driver names, package filenames, URLs, and version strings from the knowledge file.
Answer in the user's language, but keep product names, SQL, commands, paths, properties, error codes, class names, filenames, URLs, and version strings exactly as written.
When source confidence matters, preserve labels such as English-only source, english_only_auxiliary, legacy_no_downloadable_url, legacy_attachment_label_only, diagram_unavailable, not_document_format, accepted_source_limitation, and accepted_english_only_auxiliary.
Do not invent content from unavailable diagrams, missing attachments, or legacy attachment labels with no downloadable URL.
If the knowledge file does not contain enough information to answer safely, say that the available Altibase GPT knowledge does not contain the required detail."""


def repo_path(rel_path: str) -> Path:
    return REPO_ROOT / rel_path


def read_source(rel_path: str) -> str:
    return repo_path(rel_path).read_text(encoding="utf-8")


def check_required_sources() -> None:
    missing = [rel_path for rel_path in REQUIRED_SOURCE_PATHS if not repo_path(rel_path).is_file()]
    if missing:
        missing_list = "\n".join(f"- {rel_path}" for rel_path in missing)
        raise FileNotFoundError(f"Missing required source file(s):\n{missing_list}")


def append_included_document(lines: list[str], rel_path: str) -> None:
    content = read_source(rel_path).rstrip("\n")
    lines.extend(
        [
            f"BEGIN INCLUDED DOCUMENT: {rel_path}",
            content,
            f"END INCLUDED DOCUMENT: {rel_path}",
            "",
        ]
    )


def build_front_matter(build_date: str) -> list[str]:
    return [
        "---",
        "generated_file: true",
        f"generator: {SCRIPT_REL_PATH}",
        f"build_date: {build_date}",
        "source_boundary: generated llm-reference corpus only; original source trees arch/, FAQE/, DOCK/, and faq/ are evidence labels and are not GPT answer-time dependencies",
        "gpts_purpose: self-contained Altibase GPTs Knowledge upload file for customer and support answers",
        "package_status: COMPLETE_REFERENCE_PACKAGE",
        "included_document_count: 18",
        "topic_document_count: 12",
        "---",
        "",
    ]


def build_encyclopedia() -> str:
    build_date = datetime.now(timezone.utc).date().isoformat()
    lines: list[str] = []
    lines.extend(build_front_matter(build_date))
    lines.extend(
        [
            "# Altibase GPT Knowledge Encyclopedia",
            "",
            "Generated by `llm-reference/gpts-upload/build-gpts-knowledge-bundles.py` from the current generated `llm-reference/` corpus.",
            "",
            "This file is the required customer-facing GPTs Knowledge upload artifact for Altibase. Original source trees `arch/`, `FAQE/`, `DOCK/`, and `faq/` are not required at GPT answer time; source paths retained inside this file are evidence labels and maintenance traceability only.",
            "",
            "## How To Use This Knowledge File",
            "",
            "Use this encyclopedia as a self-contained `COMPLETE_REFERENCE_PACKAGE` for Altibase customer and support answers. It includes `llm-reference/README.md`, `source-index.md`, `00-source-classification.md`, all 12 topic documents in full, GPT usage guidance from `HANDOFF.md`, final validation evidence from `LLM_REFERENCE_BUILD_REPORT.md`, and accepted-risk and attachment-limitation guidance from `coverage/README.md`.",
            "",
            "The included topic corpus covers installation, upgrade, platform, architecture, storage, operation, administration, security, backup, recovery, replication, high availability, monitoring, diagnostics, troubleshooting, error messages, SQL, performance tuning, development, client API, application framework integration, migration, conversion tools, terminology, and multilingual preservation.",
            "",
            "## Answering Rules For GPTs",
            "",
            ANSWERING_RULES,
            "",
            "## Source Package Status",
            "",
            "Final source package decision: `COMPLETE_REFERENCE_PACKAGE`.",
            "",
            "The generated `llm-reference/` corpus is the source boundary for this GPTs upload file. The original source trees are not GPT answer-time dependencies. Accepted limitation labels must remain visible when source confidence matters: `English-only source`, `english_only_auxiliary`, `legacy_no_downloadable_url`, `legacy_attachment_label_only`, `diagram_unavailable`, `not_document_format`, `accepted_source_limitation`, and `accepted_english_only_auxiliary`.",
            "",
            "Do not invent unavailable diagrams, missing attachments, synthetic URLs, or source content that is not present in this knowledge file.",
            "",
        ]
    )

    for rel_path in REQUIRED_SOURCE_PATHS:
        append_included_document(lines, rel_path)

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    try:
        check_required_sources()
        UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
        content = build_encyclopedia()
        ENCYCLOPEDIA.write_text(content, encoding="utf-8", newline="\n")
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    size = ENCYCLOPEDIA.stat().st_size
    print(f"Wrote {ENCYCLOPEDIA.relative_to(REPO_ROOT)} ({size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
